name: Scan Issues in Commits

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  scan_todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Find TODOs, BUGs, FIXes, NEWs
        run: |
          mkdir -p results
          echo "Searching for issues in all relevant files..."
          # More flexible pattern that matches comments with or without spaces
          git grep -n "//.*\(TODO\|BUG\|FIX\|NEW\):[1-5]:[0-9.]\+-[0-9.]\+:" -- '*.ts' '*.tsx' ':!node_modules/**' ':!dist/**' ':!build/**' > results/issues.txt || true
          echo "Found issues (raw):"
          cat results/issues.txt || echo "No issues found"
          # Debug: Show a specific file's content
          echo "Checking AlertApi.ts content:"
          git grep -n "//" src/api/ALert/AlertApi.ts || true

      - name: Upload to Supabase
        env:
          TODO_URL: ${{ secrets.TODO_URL }}
          TODO_KEY: ${{ secrets.TODO_KEY }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python .github/scripts/upload_todos.py

      - name: Archive Issue Results
        uses: actions/upload-artifact@v4
        with:
          name: issue-results
          path: results/issues.txt
